### ISSUE TITLE
Cannot export as GLB an imported GLB because of _BumpMap

### ISSUE THREAD

**Issue by Morgan-6Freedom** [atteneder/glTFast#275]
**Describe the bug**
I import a GLB, then export it. I have an error when export.

I have an example project : https://github.com/Morgan-6Freedom/GLBExporter

**Files**

[RoueTest.zip](https://github.com/atteneder/glTFast/files/7507843/RoueTest.zip)

This is the material of the imported GLB : 
![image](https://user-images.githubusercontent.com/49686866/141001972-08db6d35-ec19-4149-80dd-aaa7c748800d.png)

**To Reproduce**
1. Import a GLB with `importer.InstantiateMainScene()`
2. Export the gameobject from the scene with `export.SaveToFileAndDispose()`
3. see error in Unity console
![image](https://user-images.githubusercontent.com/49686866/141001808-4b067233-7b82-4ef1-9657-ab411b83d85e.png)
4. Look at the export material : 
![image](https://user-images.githubusercontent.com/49686866/141001884-1b57b5bc-6fe9-4f4f-84c8-aa9b60f168f9.png)

**Expected behavior**
The exporter should be able to export a glb with a normal map and a metallic map and an occlusion map

**Desktop (please complete the following information):**
 - glTFast version 4.4.5
 - Unity Editor version 2020.3.20f
 - Render Pipeline and version Builtin pipeline
 - Platform: Editor
 
additionally (if significant for the bug):

I added that but doesn't seems to fix the issue 
![image](https://user-images.githubusercontent.com/49686866/141002193-f1495bdb-fb28-4164-9013-361c31e5a88d.png)

**Comment by atteneder** [comment]
Hi @Morgan-6Freedom ,

Thanks for the excellent report! This should be fixed in the `main` branch and it will be released as 4.4.6 soonish.

**Comment by Morgan-6Freedom** [comment]
Tried with 4.4.6
There is no error message but the _MetallicGlossMap and _OcclusionMap still doesn't export.
You can look at my [sample](https://github.com/Morgan-6Freedom/GLBExporter)

**Comment by atteneder** [comment]
@Morgan-6Freedom That's a start!

The two mentioned maps are  not supported yet. Subscribe to issue #260 for updates to export features.

**Comment by Morgan-6Freedom** [comment]
Hello. It seems that the 4.6.0 fix the occlusion map & the metallic. Does it fix the normal map ?
https://github.com/atteneder/glTFast/releases/tag/v4.6.0

**Comment by atteneder** [comment]
@Morgan-6Freedom yes, normal map export works, as stated in the [documentation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/features.md#core-gltf-features).
