### ISSUE TITLE
Normalized Positions

### ISSUE THREAD

**Issue by Kredithaichen** [atteneder/glTFast#281]
**Describe the bug**
When importing a .glb-file that was compressed with etc1s and gltf-transform meshopt into Unity via GltfAsset.cs, I am getting an exception: 'Normalized Positions will likely produce incorrect results. [...]'

**Files**
[CUBE-1.0.6.1.etc1s+meshopt.zip](https://github.com/atteneder/glTFast/files/7554838/CUBE-1.0.6.1.etc1s%2Bmeshopt.zip)

**To Reproduce**
1. set up GltfAsset-component with file-uri
2. activate the object and load in the asset
3. See error

**Expected behavior**
Various other variations on the file format and compression didn't result in errors, this one shouldn't either. 

**Screenshots**
![import-exceptions](https://user-images.githubusercontent.com/31171070/142207017-49e24068-ee0e-4203-9f2f-1d7d4f3dbc3b.png)

**Desktop (please complete the following information):**
 - glTFast version: 4.4.5
 - Unity Editor version: 2021.22f1
 - Render Pipeline and version: Universal RP 10.7.0
 - Platform: Editor

**Comment by atteneder** [comment]
@Kredithaichen  Thanks for reporting. This is fixed in 4.4.7 (due to #268).

**Comment by hybridherbst** [comment]
I'm still getting this error on 4.5.0 @atteneder. Is this expected, or should I open a new issue?

**Comment by atteneder** [comment]
@hybridherbst Thanks for the hint. No, that was a leftover....just removed it so no need for a new issue.
